[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
token = { path = "../token" }
ast = { path = "../ast" }
scanner = { path = "../scanner" }
format = { path = "../format" }
parser = { path = "../parser" }
